a = int(input("digite um valor:"))
b = int(input("digite seu segundo valor:"))
C = int(input("digite seu terceiro valor:"))
d = int(input("digite seu quarto valor:"))
diferença = (a * b - C * d)
print(diferença)
