matricula = input("Digite sua matrícula:")
horas = float(input("Número de horas trabalhadas?"))
valor = float(input("Qual valor que você recebe por hora?"))
x = ("sua matrícula é:")
y = ("seu salário é:")
print(x, matricula)
print(y, horas*valor)
