nome = input("Seu nome:")
salário = float(input("Digite seu salário fixo:"))
vendas = float(input("Digite o valor total de vendas efetuadas(em dinheiro):"))
calculo = (vendas * 15/100)
total = (salário + calculo)
print(total)
